### ISSUE TITLE
[1.1] [SQLITE_BUSY]  The database file is locked (database is locked) error

### ISSUE THREAD

**Issue by TheDeafCreeper** [whimxiqal/journey#51]
I've noticed on the 1.1 build that the database is sometimes the error in the title.

```
[15:09:43 INFO]: TheDeafCreeper issued server command: /jt Hillbilly
[15:09:43 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[15:09:43 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1030)
[15:09:43 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1042)
[15:09:43 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1007)
[15:09:43 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[15:09:43 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
[15:09:43 WARN]:        at org.sqlite.core.DB.prepare(DB.java:257)
[15:09:43 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
[15:09:43 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
[15:09:43 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[15:09:43 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
[15:09:43 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[15:09:43 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.data.sql.SqlWaypointManager.getWaypointCount(SqlWaypointManager.java:275)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.data.sql.SqlPublicWaypointManager.getCount(SqlPublicWaypointManager.java:87)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.scope.ScopeManager.lambda$registerDefault$5(ScopeManager.java:66)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.ScopeImpl.destinations(ScopeImpl.java:78)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.search.InternalScope.lambda$new$5(InternalScope.java:69)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.search.InternalScope.sessions(InternalScope.java:82)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.scope.ScopeUtil.session(ScopeUtil.java:162)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.scope.ScopeUtil.locationFromSubScopes(ScopeUtil.java:212)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.scope.ScopeUtil.session(ScopeUtil.java:187)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.scope.ScopeUtil.session(ScopeUtil.java:153)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.command.JourneyExecutor$1.visitJourneytoTarget(JourneyExecutor.java:112)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.command.JourneyExecutor$1.visitJourneytoTarget(JourneyExecutor.java:69)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.common.JourneyParser$JourneytoTargetContext.accept(JourneyParser.java:1700)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.libs.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.command.JourneyExecutor$1.visitJourneyto(JourneyExecutor.java:92)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.command.JourneyExecutor$1.visitJourneyto(JourneyExecutor.java:69)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.common.JourneyParser$JourneytoContext.accept(JourneyParser.java:260)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.libs.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.libs.mantle.common.MantleCommand.process(MantleCommand.java:124)
[15:09:43 WARN]:        at Journey-Bukkit-1.0.2-dev-ed6e83f.jar//net.whimxiqal.journey.libs.mantle.paper.PaperMantleCommand.execute(PaperMantleCommand.java:90)
[15:09:43 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[15:09:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962)
[15:09:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[15:09:43 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[15:09:43 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:313)
[15:09:43 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:297)
[15:09:43 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2386)
[15:09:43 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2340)
[15:09:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[15:09:43 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:09:43 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:09:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:09:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:09:43 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1368)
[15:09:43 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[15:09:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:09:43 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1345)
[15:09:43 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1338)
[15:09:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:09:43 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1416)
[15:09:43 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1194)
[15:09:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[15:09:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:09:43 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'jt Hillbilly' in net.whimxiqal.journey.libs.mantle.paper.PaperMantleCommand(journeyto)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.whimxiqal.journey.data.DataAccessException
        at net.whimxiqal.journey.data.sql.SqlWaypointManager.getWaypointCount(SqlWaypointManager.java:295) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.data.sql.SqlPublicWaypointManager.getCount(SqlPublicWaypointManager.java:87) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.scope.ScopeManager.lambda$registerDefault$5(ScopeManager.java:66) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.ScopeImpl.destinations(ScopeImpl.java:78) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.search.InternalScope.lambda$new$5(InternalScope.java:69) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.search.InternalScope.sessions(InternalScope.java:82) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.scope.ScopeUtil.session(ScopeUtil.java:162) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.scope.ScopeUtil.locationFromSubScopes(ScopeUtil.java:212) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.scope.ScopeUtil.session(ScopeUtil.java:187) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.scope.ScopeUtil.session(ScopeUtil.java:153) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.command.JourneyExecutor$1.visitJourneytoTarget(JourneyExecutor.java:112) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.command.JourneyExecutor$1.visitJourneytoTarget(JourneyExecutor.java:69) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.common.JourneyParser$JourneytoTargetContext.accept(JourneyParser.java:1700) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.libs.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.command.JourneyExecutor$1.visitJourneyto(JourneyExecutor.java:92) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.command.JourneyExecutor$1.visitJourneyto(JourneyExecutor.java:69) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.common.JourneyParser$JourneytoContext.accept(JourneyParser.java:260) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.libs.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.libs.mantle.common.MantleCommand.process(MantleCommand.java:124) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.libs.mantle.paper.PaperMantleCommand.execute(PaperMantleCommand.java:90) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

**Comment by whimxiqal** [comment]
Fixed with #55
