### ISSUE TITLE
[1.1] Asynchronous Chunk getEntities call

### ISSUE THREAD

**Issue by TheDeafCreeper** [whimxiqal/journey#54]
```
[17:06:41 ERROR]: Thread Craft Scheduler Thread - 824 - Journey failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2523) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1983) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.getEntity(CraftServer.java:2595) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at org.bukkit.Bukkit.getEntity(Bukkit.java:2060) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.whimxiqal.journey.bukkit.BukkitPlatformProxy.entityCellLocation(BukkitPlatformProxy.java:142) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.command.JourneyExecutor$1.destinationSearch(JourneyExecutor.java:348) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.command.JourneyExecutor$1.lambda$personalWaypointSearch$10(JourneyExecutor.java:331) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:06:41 WARN]: [Journey] Plugin Journey v1.0.2-dev-ed6e83f generated an exception while executing task 12446829
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2523) ~[?:?]
        at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1983) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.getEntity(CraftServer.java:2595) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at org.bukkit.Bukkit.getEntity(Bukkit.java:2060) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.whimxiqal.journey.bukkit.BukkitPlatformProxy.entityCellLocation(BukkitPlatformProxy.java:142) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.command.JourneyExecutor$1.destinationSearch(JourneyExecutor.java:348) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at net.whimxiqal.journey.command.JourneyExecutor$1.lambda$personalWaypointSearch$10(JourneyExecutor.java:331) ~[Journey-Bukkit-1.0.2-dev-ed6e83f.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1838]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by whimxiqal** [comment]
Fixed with #55
