### ISSUE TITLE
Broken 1.20.1 Support

### ISSUE THREAD

**Issue by ItsMrConnor** [whimxiqal/journey#66]
I'm not sure where to start but can someone look into this? Thanks

> [01:45:00] [Server thread/INFO]: [Journey] Enabling Journey v1.1.0
[01:45:00] [Server thread/INFO]: [Journey] Initializing Journey...
[01:45:00] [Server thread/ERROR]: Error occurred while enabling Journey v1.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/ComponentLike
	at net.whimxiqal.journey.Journey.<init>(Journey.java:49) ~[?:?]
	at net.whimxiqal.journey.Journey.create(Journey.java:69) ~[?:?]
	at net.whimxiqal.journey.bukkit.JourneyBukkit.onEnable(JourneyBukkit.java:69) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3810-Spigot-c62f4bd-b6b514b]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3810-Spigot-c62f4bd-b6b514b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3810-Spigot-c62f4bd-b6b514b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3810-Spigot-c62f4bd-b6b514b]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3810-Spigot-c62f4bd-b6b514b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3810-Spigot-c62f4bd-b6b514b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3810-Spigot-c62f4bd-b6b514b]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.ComponentLike
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 14 more

**Comment by whimxiqal** [comment]
Are you running on Spigot? Unfortunately, Journey is currently only supported on Paper and Paper forks.
