### ISSUE TITLE
Problem with the path across the bridge

### ISSUE THREAD

**Issue by legendofgow** [whimxiqal/journey#73]
Hello, I have a problem with the bridge, the plugin does not want to create a path to lead the player past the bridge shown in the screenshot, what can I change in such a situation? bridge material?

`[11:29:20 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 24 out of bounds for length 24
[11:29:20 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftChunkSnapshot.getBlockData(CraftChunkSnapshot.java:109)
[11:29:20 WARN]:        at Journey-Bukkit-1.2.0.jar//net.whimxiqal.journey.bukkit.chunk.BukkitSessionJourneyChunk.block(BukkitSessionJourneyChunk.java:51)
[11:29:20 WARN]:        at Journey-Bukkit-1.2.0.jar//net.whimxiqal.journey.chunk.ChunkCacheBlockProvider.toBlock(ChunkCacheBlockProvider.java:66)
[11:29:20 WARN]:        at Journey-Bukkit-1.2.0.jar//net.whimxiqal.journey.navigation.mode.FlyMode.getDestinations(FlyMode.java:79)
[11:29:20 WARN]:        at Journey-Bukkit-1.2.0.jar//net.whimxiqal.journey.search.PathTrial.runSafe(PathTrial.java:283)
[11:29:20 WARN]:        at Journey-Bukkit-1.2.0.jar//net.whimxiqal.journey.search.PathTrial.run(PathTrial.java:195)
[11:29:20 WARN]:        at Journey-Bukkit-1.2.0.jar//net.whimxiqal.journey.manager.DistributedWorkManager$WorkItemExecutor.run(DistributedWorkManager.java:118)
[11:29:20 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:29:20 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:29:20 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:29:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:29:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:29:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[11:29:20 ERROR]: [Journey] [Destination Path Search] {session: bcd17bfe-1810-4477-bb7e-14c472524035, origin: {x: -43, y: 173, z: -45, domain: 1}, destination: {x: 27, y: 174, z: -160, domain: 1}, cycles: 9756, state: running, visited: 9757478, from cache: false}: A java.lang.ArrayIndexOutOfBoundsException occurred, failing
![2024-01-23_11 36 57]
`
![2024-01-23_11 36 57](https://github.com/whimxiqal/journey/assets/88216155/5e149e37-7714-45d3-942f-c1aaf55e14d5)

**Comment by whimxiqal** [comment]
I'll have to look at the source code for Paper's `CraftChunkSnapshot`, but this is definitely not an issue that can be solved by you changing up the bridge. It's either a bug on my end or Paper's end. Thanks for reporting
